server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://47.100.206.112:3306/yami_shops?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: yami_shops
    password: m22TppxFYt4dW2Kh
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      password: 123456
      port: 6379
      database: 0
logging:
  config: classpath:logback/logback-dev.xml
xxl-job:
  accessToken: default_token
  logPath: /data/applogs/xxl-job/jobhandler
  admin:
    addresses: http://localhost:8080/xxl-job-admin

# 支付宝配置
alipay:
  appId: 2021005195608528
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCFffGP9ia9Vpa+JF50k5255hNhX0VxEYgpUHi1DQG67AjNfeMUuaJ8XDaX39DlgqE6PUyEN7R6mdiypzcRX7UXRrXiuWLYhm96KENIh+v5SbALDbZUQgQnRMbVXeFtC21WrxzP6v0jsyLwtTgk3Js7/1mBcV12rZG3N4UkEbN+ySHzCaFNOep/CCxXLYnUuI7NK1zAIGBGGQ0mNgDcdg9cRAD09bnSLiuNWfaeh46DIt0LFWyi1ql+lPJdFOSrXjHa4Be/mNeNXBh1Csbr8gkDqs/SK8uXjh1j4dl1IpljSKAKk+aOrlrUN7H1TFgttRxGZRJx3nxBQ0wBJcwfF0eRAgMBAAECggEAXft5Yl1ukMaxglSgm3qCBStSYa9teFlbf5rEINNzcGJVIDeM9D5tgxh45xwQOkVptVMK19tQGTDPO5g2UOkM2cJSs7jJOqALQ/msxRfMrsmOQ3n38AI6YlstkXJzDw6IgArxQgCzD7tC0i0Dxg/6ypbQMS3bG36/pDpWZjqAILXymISbYXmzQQx1V1tsnLzGkUV/2EXHwGjtgG9VdwL8inNS1FHrXibpzayhlk0F+MpphpGUzl7hM4cnJg5lTpmAQyIlERZGFLoZ9tSdjVTMWxRxrVP6KrfQkXkEaKuY610XGa/YukUEAyYk4WxK3IraL8/71QrbBJgKJhY3DOyEMQKBgQD4RyOO6Fn5L++zfXUiaGdzJTh9KQqO/3VI+yQ8vmkqsWhQT7ng65uCwylIuAQeuV3vN0yxvvO0fkwuiSpZmgi4pbheuI8cQBlRPjYk/StF/JetA0K+N9ibiuQrVUDnFfdo8D2umPlziyapMW370ajep07y6iyBCvEe/ETInKXOqwKBgQCJpNh9dxyXybzM5coMQIWOAcPF4WbSryTxabG/SdXVhgpJ9XsOOxg4EQ/nYxeet4vhGuV+/ZxAYOPK7Eageo8dqBpth7JFuiPqHn4N5Hc2KtLh0PzDQWHGmGv4dnrdshuxhy2/LAa3s7c3uoTJdRKHSdodSGg7iBByOm3vXN9SswKBgQCb06J4tlKKOND8Wbij8N1FAs5yl8i9uY42URIMYgIFvrVW+sMSbS38o1sM/hnv4q4XTyD+yneRCFfuOT7wX+Irai/Om42O0JhTSnWXP6LiWUglWc+RLeHwtfrBS8/hegL/xREhvXeLUoHgXVrHW27e2CmQAvQNxf1SUkkllFPo4wKBgHnPZr9x/93cbLcvzKUXHJpVuXmPRj3BPgJfNSxCHXj/TG+zTRmE9qP3hYmSSj7t1F58PQkrS3I1zKGyg7ZVf/4Q3IJ+Cihm2I3COm/09gL71vB80JPDctIb5cFWqNk1XAi5xqReQ/uikcxBxm26q5EKrHopsASvH07Xop6oJAK9AoGAfmOxcOEr3uEJYpq/yPIO4owo2NX3Gf6mBhNXec6k6U0zhLCPbHw6J7PJ3rk0tETIXFdS8szbc3rL2sMNsJaVx5Y04nZNVrC/ggFIrDATQT5hmd4y/t6u3tNTDYrVE1kq2YOAJxkAFjBOPtcUvxylYNH8VEg5zh63GoAEQTeAwBk=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjhUcgM530SFIWBoDSU51mszwWXetotcKa7EN1g2hhs5Sa/lLrMGJhGrtAVd6E6fr63li9hNWldDvrkoehvHWxCj8cTO+8mbb2rfg5Pn11YxsPQsN4m2BWvyC+NO5x3KjD5dLjB/ptuh4eiLZnP/jp/TqdVppvossIRzB6+tEpvUyFKfdCJLLFCwnfQtpPo9TFzAVVpby5dTvmqtxRXd2hPdtGV+dtjoair+Psk+BwCKNilfEJAvqSjYqL1GDVdHjfTKlQJwYZnLrGIugV8juvFbYDfBhRy2vwlA0cPFtzd5YNRjuNAPWJLrsz3aJI8TC3TiMRJUxI1FEjj8NNn0LAQIDAQAB
  serverUrl: https://openapi.alipay.com/gateway.do
  notifyUrl: http://shunjinmy.com/api-admin/alipay/notify
  returnUrl: http://shunjinmy.com/pages/pay-result/pay-result
